### ISSUE TITLE
Sophos security Threat

### ISSUE THREAD

**Issue by GianlucaVeschi** [iamzoka/refreshd-website#1]
Hello,
I have tried to access your website but Sophos Antivirus throws this error.
"Access has been blocked as the threat Mal/HTMLGen-A has been found on this website"

Maybe it's a false positive but I thought you'd want to check it out.

**Comment by iamzoka** [comment]
Hey, I've refactored the whole site, removed all of the old files, so it should be ok now. Thank you for reporting it and sorry for replying so late, I appreciate the gesture very much.

Cheers! 🍻
